# Homework 5

- Student name: Byron Washington
- Email: ********
- G-number: ********

## Imported packages

In [29]:
import math
import random
import numpy as np

## Question 1

In [30]:
def rel (t, v, c):
	under_root = 1 - ((v**2)/(c**2))
	final = t * (1 / math.sqrt(under_root))
	return final
ans = rel(1,2,5)
print(str(ans))    

1.0910894511799618


---

## Question 2

In [31]:
myList = []
for i in range(1000):
    myList.append(random.randint(-10, 10))
final = sum(myList) / len(myList)
print("The average of 1000 random numbers between -10 and 10 is " + str(final))

The average of 1000 random numbers between -10 and 10 is -0.01


This makes sense because the average of -10 and 10 is 0 so any amount of numbers set between those bounds should average out to 0

---

## Question 3

In [32]:
numbers = [41, 33, 11, 9, 7, 11, 21, 19, 7, 11, 6, 9, 30, 24, 1, 5, 7, 4, 35, 3, 35, 1, 18, 38, 11, 9, 11, 7, 9, 33, 11, 3, 40, 16, 11, 1, 33, 7, 29, 9, 7, 11]
answer = {} # using dictionary seems easier for me since i can keep a key value for each time it's seen
for i in numbers:
    if i not in answer:
        answer.update({i : 1})
    else:
        current_amount = answer[i]
        answer.update({i : current_amount + 1})
for x in sorted(answer):
    print("Number " + str(x) + " appears " + str(answer[x]) + " times")

Number 1 appears 3 times
Number 3 appears 2 times
Number 4 appears 1 times
Number 5 appears 1 times
Number 6 appears 1 times
Number 7 appears 6 times
Number 9 appears 5 times
Number 11 appears 8 times
Number 16 appears 1 times
Number 18 appears 1 times
Number 19 appears 1 times
Number 21 appears 1 times
Number 24 appears 1 times
Number 29 appears 1 times
Number 30 appears 1 times
Number 33 appears 3 times
Number 35 appears 2 times
Number 38 appears 1 times
Number 40 appears 1 times
Number 41 appears 1 times


---

## Question 4

In [33]:
test_lists = [
    [2, -1, 10, 5],
    [10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10],
    [4],
    [1, 1, 2, 3, 5, 8, 13]
]
def list_stats(lists):
    minimum = min(lists)
    maximum = max(lists)
    average = int(sum(lists) / len(lists))
    return minimum, maximum, average

for i in test_lists:
    lowest, highest, mean = list_stats(i)
    print(i)
    print("Minimum: " + str(lowest) + ", Maximum: " + str(highest) + ", Average: " + str(mean) + "\n")

[2, -1, 10, 5]
Minimum: -1, Maximum: 10, Average: 4

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10]
Minimum: -10, Maximum: 10, Average: 0

[4]
Minimum: 4, Maximum: 4, Average: 4

[1, 1, 2, 3, 5, 8, 13]
Minimum: 1, Maximum: 13, Average: 4



---

## Question 5

In [34]:
arr1 = np.random.randint(0, 100, 10)
print(arr1)

arr2 = np.random.randint(0, 100, 10)
print(arr2)

def separate(array1, array2):
    all_elements = np.concatenate((array1, array2))
    oddArr = all_elements[all_elements % 2 != 0]
    evenArr = all_elements[all_elements % 2 == 0]
    return oddArr, evenArr

print(separate(arr1, arr2))

[29  4 52  4 64 33 43 25  0 69]
[44 75 45 42 10 41 59 18  8  4]
(array([29, 33, 43, 25, 69, 75, 45, 41, 59], dtype=int32), array([ 4, 52,  4, 64,  0, 44, 42, 10, 18,  8,  4], dtype=int32))
